### ISSUE TITLE
Refactor Code

### ISSUE THREAD

**Issue by VdotR** [VdotR/SnapPoll#2]
- Refactor API to restrict sensitive data coming out (poll correct option etc)
- Make sure all URLs are in config
- Possibly move all fetch functions to utility file
- Split css into multiple files

**Comment by cbaeucsd** [comment]
Refactor API to restrict sensitive data coming out (poll correct option etc) - Done

**Comment by cbaeucsd** [comment]
title bit too vague to close right now, we'll work on that next time i guess
still stuff that I haven't touched yet that I might
